fcm:
  firebase:
    dryRun: false
    app:
      url: https://rfaitateste2.firebaseio.com
    path:
      serviceAccountKey: ${HOME}/serviceAccountKey.json
  rabbitmq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest
  mongodb:
    hostname: localhost
    port: 27017
    database: test2
  send:
    topic:
      exchange: fcm.send.topic.exchange
      sendDLQQueue: fcm.send.topic.sendDLQQueue
      sendQueue: fcm.send.topic.sendQueue
    token:
      exchange: fcm.send.token.exchange
      sendDLQQueue: fcm.send.token.sendDLQQueue
      sendQueue: fcm.send.token.sendQueue

server:
  port: 8080
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: docker-compose
fcm:
  rabbitmq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest
  mongodb:
    hostname: mongodb
    port: 27017
    database: test2