spring:
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

#use this when there is not a eureka instance running
fcm-service:
  ribbon:
    listOfServers: localhost:8084

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        timeout:
          enabled: false

server:
  port: 9084
  compression:
    enabled: true